# Generated by Django 6.0.6 on 2026-07-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='voice_metrics_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
